services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gestionstock
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gestionstock
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

